### ISSUE TITLE
Not reporting any issues?

### ISSUE THREAD

**Issue by AndreaCrotti** [andrewhr/codeclimate-kibit#5] opened 2017-11-01 11:26 UTC
I tried this engine now in a couple of different projects, and while it doesn't fail, it doesn't seem to work either.

Both projects report several issues when running kibit locally, but in codeclimate no issues come up at all.
I assumed I was doing something wrong but another colleague had the same issue, so I wonder if this engine is actually producing the same results as running kibit locally in theory?

**Comment by martinzuern** [comment] 2017-12-13 13:46
Same here. Steps to reproduce:
- run `lein kibit`, which returns multiple issues
- Add a .code-climate.yml file, contents 
  ```
  engines:
    kibit:
      enabled: true
  ```
- run `codeclimate analyze`

It returns 0 issues, even though `lein kibit` returns issues.

**Comment by dblandin** [comment] 2018-08-30 17:43
Hi there! :wave: 

I'm an engineer at Code Climate and wanted to provide a quick update.

@lukaszkorecki put in some great work to fix this in https://github.com/andrewhr/codeclimate-kibit/pull/6.

I've gone ahead and updated the plugin on Code Climate with an image built from his fork, including the changes in the PR.

If you're interested in giving this plugin another try, please let us know how it goes!

Thanks!

**Comment by andrewhr** [comment] 2018-09-04 03:52
I've merged #6, so even the custom image shouldn't be necessary anymore (I don't know how that's handled on you side @dblandin, but I hope things are cleaner now).

**Closed as completed by andrewhr** 2018-09-04 03:52 UTC

**Comment by AndreaCrotti** [comment] 2018-09-04 07:22
I tried it on one of my personal projects and it works now thanks!

I can't actually make it report anything to the PRs directly though, but that might be just some setting I'm missing which I haven't found yet.

**Comment by lukaszkorecki** [comment] 2018-09-04 09:30
@AndreaCrotti I believe it's due to this issue: https://github.com/lukaszkorecki/codeclimate-kibit/commit/09bad249df089764055f657dc94f409f6393a7cf#diff-84bc02327a52243d073d7893a93515ebR29
I've noticed that all paths in CodeClimate UI with Kibit reports start with `./src/...` - removing the `./` should fix it. There's a similar issue in code coverage reporting when using Cloverage out of the box - I had to do some output mangling to make it work as expected https://gist.github.com/lukaszkorecki/60093e57cbb4b178547e4a7ff23c703d#file-circle-yml-L41-L48

Lastly - what's running in CodeClimate's infra is not the latest version (or it wasn't as of yesterday) as I noticed the path issue and fixed in the afternoon. 

@dblandin - I've submitted the form requesting engine update, we can take this off GitHub and manage via email 👍

**Comment by dblandin** [comment] 2018-09-04 14:41
@lukaszkorecki Feel free to join our developer program if you haven't already: https://codeclimate.com/dev_form

You'll receive an invite to our codeclimate-community slack organization where we can continue the conversation. :+1: 

I'll queue up another plugin update! Thanks!
